/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as DevIdCardEditorRouteImport } from './routes/dev/id-card-editor'
import { Route as AuthedActivityRouteImport } from './routes/_authed/activity'
import { Route as AuthedAdminRouteImport } from './routes/_authed/_admin'
import { Route as AuthedVouchersIndexRouteImport } from './routes/_authed/vouchers/index'
import { Route as AuthedBenefitsIndexRouteImport } from './routes/_authed/benefits/index'
import { Route as AuthedPeoplePersonIdRouteImport } from './routes/_authed/people.$personId'
import { Route as AuthedBenefitsBenefitIdRouteImport } from './routes/_authed/benefits/$benefitId'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/_admin/users'
import { Route as AuthedVouchersReleaseBenefitIdRouteImport } from './routes/_authed/vouchers/release.$benefitId'
import { Route as AuthedVouchersProvideBenefitIdRouteImport } from './routes/_authed/vouchers/provide.$benefitId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const DevIdCardEditorRoute = DevIdCardEditorRouteImport.update({
  id: '/dev/id-card-editor',
  path: '/dev/id-card-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedActivityRoute = AuthedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedVouchersIndexRoute = AuthedVouchersIndexRouteImport.update({
  id: '/vouchers/',
  path: '/vouchers/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBenefitsIndexRoute = AuthedBenefitsIndexRouteImport.update({
  id: '/benefits/',
  path: '/benefits/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeoplePersonIdRoute = AuthedPeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBenefitsBenefitIdRoute = AuthedBenefitsBenefitIdRouteImport.update({
  id: '/benefits/$benefitId',
  path: '/benefits/$benefitId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedVouchersReleaseBenefitIdRoute =
  AuthedVouchersReleaseBenefitIdRouteImport.update({
    id: '/vouchers/release/$benefitId',
    path: '/vouchers/release/$benefitId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedVouchersProvideBenefitIdRoute =
  AuthedVouchersProvideBenefitIdRouteImport.update({
    id: '/vouchers/provide/$benefitId',
    path: '/vouchers/provide/$benefitId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/activity': typeof AuthedActivityRoute
  '/dev/id-card-editor': typeof DevIdCardEditorRoute
  '/': typeof AuthedIndexRoute
  '/users': typeof AuthedAdminUsersRoute
  '/benefits/$benefitId': typeof AuthedBenefitsBenefitIdRoute
  '/people/$personId': typeof AuthedPeoplePersonIdRoute
  '/benefits': typeof AuthedBenefitsIndexRoute
  '/vouchers': typeof AuthedVouchersIndexRoute
  '/vouchers/provide/$benefitId': typeof AuthedVouchersProvideBenefitIdRoute
  '/vouchers/release/$benefitId': typeof AuthedVouchersReleaseBenefitIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/activity': typeof AuthedActivityRoute
  '/dev/id-card-editor': typeof DevIdCardEditorRoute
  '/': typeof AuthedIndexRoute
  '/users': typeof AuthedAdminUsersRoute
  '/benefits/$benefitId': typeof AuthedBenefitsBenefitIdRoute
  '/people/$personId': typeof AuthedPeoplePersonIdRoute
  '/benefits': typeof AuthedBenefitsIndexRoute
  '/vouchers': typeof AuthedVouchersIndexRoute
  '/vouchers/provide/$benefitId': typeof AuthedVouchersProvideBenefitIdRoute
  '/vouchers/release/$benefitId': typeof AuthedVouchersReleaseBenefitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/_admin': typeof AuthedAdminRouteWithChildren
  '/_authed/activity': typeof AuthedActivityRoute
  '/dev/id-card-editor': typeof DevIdCardEditorRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/_admin/users': typeof AuthedAdminUsersRoute
  '/_authed/benefits/$benefitId': typeof AuthedBenefitsBenefitIdRoute
  '/_authed/people/$personId': typeof AuthedPeoplePersonIdRoute
  '/_authed/benefits/': typeof AuthedBenefitsIndexRoute
  '/_authed/vouchers/': typeof AuthedVouchersIndexRoute
  '/_authed/vouchers/provide/$benefitId': typeof AuthedVouchersProvideBenefitIdRoute
  '/_authed/vouchers/release/$benefitId': typeof AuthedVouchersReleaseBenefitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/activity'
    | '/dev/id-card-editor'
    | '/'
    | '/users'
    | '/benefits/$benefitId'
    | '/people/$personId'
    | '/benefits'
    | '/vouchers'
    | '/vouchers/provide/$benefitId'
    | '/vouchers/release/$benefitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/activity'
    | '/dev/id-card-editor'
    | '/'
    | '/users'
    | '/benefits/$benefitId'
    | '/people/$personId'
    | '/benefits'
    | '/vouchers'
    | '/vouchers/provide/$benefitId'
    | '/vouchers/release/$benefitId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/_admin'
    | '/_authed/activity'
    | '/dev/id-card-editor'
    | '/_authed/'
    | '/_authed/_admin/users'
    | '/_authed/benefits/$benefitId'
    | '/_authed/people/$personId'
    | '/_authed/benefits/'
    | '/_authed/vouchers/'
    | '/_authed/vouchers/provide/$benefitId'
    | '/_authed/vouchers/release/$benefitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  DevIdCardEditorRoute: typeof DevIdCardEditorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/dev/id-card-editor': {
      id: '/dev/id-card-editor'
      path: '/dev/id-card-editor'
      fullPath: '/dev/id-card-editor'
      preLoaderRoute: typeof DevIdCardEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/activity': {
      id: '/_authed/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthedActivityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_admin': {
      id: '/_authed/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/vouchers/': {
      id: '/_authed/vouchers/'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof AuthedVouchersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/benefits/': {
      id: '/_authed/benefits/'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof AuthedBenefitsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/people/$personId': {
      id: '/_authed/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AuthedPeoplePersonIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/benefits/$benefitId': {
      id: '/_authed/benefits/$benefitId'
      path: '/benefits/$benefitId'
      fullPath: '/benefits/$benefitId'
      preLoaderRoute: typeof AuthedBenefitsBenefitIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_admin/users': {
      id: '/_authed/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/vouchers/release/$benefitId': {
      id: '/_authed/vouchers/release/$benefitId'
      path: '/vouchers/release/$benefitId'
      fullPath: '/vouchers/release/$benefitId'
      preLoaderRoute: typeof AuthedVouchersReleaseBenefitIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/vouchers/provide/$benefitId': {
      id: '/_authed/vouchers/provide/$benefitId'
      path: '/vouchers/provide/$benefitId'
      fullPath: '/vouchers/provide/$benefitId'
      preLoaderRoute: typeof AuthedVouchersProvideBenefitIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedActivityRoute: typeof AuthedActivityRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedBenefitsBenefitIdRoute: typeof AuthedBenefitsBenefitIdRoute
  AuthedPeoplePersonIdRoute: typeof AuthedPeoplePersonIdRoute
  AuthedBenefitsIndexRoute: typeof AuthedBenefitsIndexRoute
  AuthedVouchersIndexRoute: typeof AuthedVouchersIndexRoute
  AuthedVouchersProvideBenefitIdRoute: typeof AuthedVouchersProvideBenefitIdRoute
  AuthedVouchersReleaseBenefitIdRoute: typeof AuthedVouchersReleaseBenefitIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedActivityRoute: AuthedActivityRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedBenefitsBenefitIdRoute: AuthedBenefitsBenefitIdRoute,
  AuthedPeoplePersonIdRoute: AuthedPeoplePersonIdRoute,
  AuthedBenefitsIndexRoute: AuthedBenefitsIndexRoute,
  AuthedVouchersIndexRoute: AuthedVouchersIndexRoute,
  AuthedVouchersProvideBenefitIdRoute: AuthedVouchersProvideBenefitIdRoute,
  AuthedVouchersReleaseBenefitIdRoute: AuthedVouchersReleaseBenefitIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  DevIdCardEditorRoute: DevIdCardEditorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
